NewtonInterpolation:Newton_Interpolation.o
	g++ -o NewtonInterpolation Newton_Interpolation.o
Newton_Interpolation.o:Newton_Interpolation.cpp
	g++ -c Newton_Interpolation.cpp
clean:
	rm NewtonInterpolation Newton_Interpolation.o