PolynomialDivide:Polynomial_divide.o
	g++ -o PolynomialDivide Polynomial_divide.o
Polynomial_divide.o:Polynomial_divide.cpp
	g++ -c Polynomial_divide.cpp
clean:
	rm PolynomialDivide Polynomial_divide.o